version: "3.7"
services:
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: Password1
    networks:
      - archesky
  postgres-server:
    image: library/postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Password1
    networks:
      - archesky
  keycloak-server:
    image: jboss/keycloak:latest
    ports:
      - "8180:8080"
    environment:
      DB_ADDR: postgres-server
      DB_PORT: 5432
      DB_USER: postgres
      DB_VENDOR: postgres
      DB_PASSWORD: Password1
      DB_DATABASE: postgres
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: Password1
    links:
      - postgres-server
    depends_on:
      - postgres-server
    networks:
      - archesky
networks:
  traefik:
  archesky:
